"""IK correctness by round-tripping through FK, plus the refusal cases.

An arm that goes "roughly there" is worse than one that refuses, so the
unreachable cases get as much attention as the reachable ones.
"""
import math
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from hr_arm_controller.kinematics import (ArmGeometry, JointLimits,  # noqa: E402
                                          Unreachable, forward, interpolate,
                                          inverse, solve, wrap_angle)

G = ArmGeometry(base_height=0.10, shoulder_offset=0.02,
                upper_arm=0.15, forearm=0.14, wrist_length=0.08)
L = JointLimits()


def round_trip(position, pitch, roll=0.0):
    joints = solve(position, pitch, G, L, roll)
    back, _, back_pitch = forward(joints, G)
    return joints, back, back_pitch


# Poses generated by running FK on plausible joint angles: reachability is then
# guaranteed by construction, and the test measures the solver rather than the
# author's ability to guess a reachable point.
POSES = [(0.0, 0.0, 0.0), (0.6, 0.2, -0.4), (-0.8, 0.5, -0.9),
         (1.57, 0.1, -0.3), (0.0, 0.8, -1.4), (-1.2, -0.2, 0.3),
         (0.3, 0.9, -1.6), (2.0, 0.4, -0.7)]


@pytest.mark.parametrize('seed', POSES)
def test_ik_round_trips_through_fk(seed):
    """IK must land on the pose FK produced, whichever branch it picks."""
    j1, j2, j3 = seed
    j5 = -(j2 + j3) * 0.5
    joints = (j1, j2, j3, 0.0, j5, 0.0)
    position, _, pitch = forward(joints, G)
    _, back, back_pitch = round_trip(position, pitch)
    assert back == pytest.approx(position, abs=1e-6)
    assert wrap_angle(back_pitch - pitch) == pytest.approx(0.0, abs=1e-6)


def test_fk_of_the_zero_pose_is_straight_out():
    (x, y, z), yaw, pitch = forward((0.0,) * 6, G)
    assert y == pytest.approx(0.0)
    assert x == pytest.approx(G.shoulder_offset + G.upper_arm + G.forearm + G.wrist_length)
    assert z == pytest.approx(G.base_height)
    assert (yaw, pitch) == (0.0, 0.0)


def test_fk_rejects_a_wrong_joint_count():
    with pytest.raises(ValueError, match='6 joints'):
        forward((0.0, 0.0, 0.0), G)


def test_base_yaw_follows_the_target_bearing():
    joints = solve((0.0, 0.22, 0.12), 0.0, G, L)
    assert joints[0] == pytest.approx(math.pi / 2, abs=1e-6)


def test_target_beyond_reach_is_refused():
    with pytest.raises(Unreachable) as exc:
        solve((2.0, 0.0, 0.10), 0.0, G, L)
    assert exc.value.reason == 'out_of_reach'


def test_target_inside_minimum_reach_is_refused():
    tight = ArmGeometry(base_height=0.10, shoulder_offset=0.0,
                        upper_arm=0.30, forearm=0.10, wrist_length=0.0)
    with pytest.raises(Unreachable) as exc:
        solve((0.05, 0.0, 0.10), 0.0, tight, L)
    assert exc.value.reason == 'inside_minimum_reach'


def test_reach_boundary_is_solvable_but_just_beyond_is_not():
    edge = G.shoulder_offset + G.max_reach() + G.wrist_length
    solve((edge - 1e-6, 0.0, G.base_height), 0.0, G, L)
    with pytest.raises(Unreachable):
        solve((edge + 1e-3, 0.0, G.base_height), 0.0, G, L)


def test_joint_limits_are_enforced():
    narrow = JointLimits(lower=(-0.1,) * 6, upper=(0.1,) * 6)
    with pytest.raises(Unreachable) as exc:
        solve((0.0, 0.22, 0.12), 0.0, G, narrow)
    assert exc.value.reason == 'joint_limit'
    assert 'joints 1' in str(exc.value)


def test_limit_check_reports_every_offending_joint():
    assert JointLimits(lower=(0.0,) * 6, upper=(0.1,) * 6).violations(
        (0.5, 0.05, -0.5, 0.0, 0.0, 0.0)) == (0, 2)


def test_elbow_up_is_preferred_when_both_solutions_exist():
    up = inverse((0.22, 0.0, 0.12), 0.0, G, L, elbow_up=True)
    down = inverse((0.22, 0.0, 0.12), 0.0, G, L, elbow_up=False)
    assert up[2] > 0 and down[2] < 0
    assert solve((0.22, 0.0, 0.12), 0.0, G, L) == pytest.approx(up)


def test_elbow_down_is_used_when_elbow_up_breaks_a_limit():
    """Reachability and limits are different failures and must not be conflated."""
    limits = JointLimits(lower=(-3.14, -1.92, -2.36, -3.14, -1.92, -3.14),
                         upper=(3.14, 1.92, 0.0, 3.14, 1.92, 3.14))
    joints = solve((0.22, 0.0, 0.12), 0.0, G, limits)
    assert joints[2] <= 0.0


def test_roll_is_passed_through_to_the_last_joint():
    assert solve((0.22, 0.0, 0.12), 0.0, G, L, roll=1.0)[5] == pytest.approx(1.0)


def test_downward_approach_round_trips():
    """Grasping off a table means pointing the tool down."""
    _, back, back_pitch = round_trip((0.20, 0.0, 0.05), -math.pi / 2)
    assert back == pytest.approx((0.20, 0.0, 0.05), abs=1e-6)
    assert back_pitch == pytest.approx(-math.pi / 2, abs=1e-6)


def test_interpolation_hits_both_ends():
    path = interpolate((0.0,) * 6, (1.0,) * 6, 5)
    assert len(path) == 5
    assert path[0] == pytest.approx((0.0,) * 6)
    assert path[-1] == pytest.approx((1.0,) * 6)
    assert path[2] == pytest.approx((0.5,) * 6)


def test_interpolation_needs_at_least_two_steps():
    with pytest.raises(ValueError, match='at least 2'):
        interpolate((0.0,) * 6, (1.0,) * 6, 1)


def test_wrap_angle_stays_in_range():
    for a in (-10.0, -math.pi, 0.0, math.pi, 10.0):
        assert -math.pi - 1e-9 <= wrap_angle(a) <= math.pi + 1e-9
