#ifndef HR_PROTOCOL_CONFIG_H
#define HR_PROTOCOL_CONFIG_H
#define HR_PROTOCOL_VERSION 1u
#define HR_PROTOCOL_MAX_PAYLOAD 96u
#define HR_UPPER_COMMAND_TIMEOUT_MS 150u
#define HR_UPPER_HEARTBEAT_TIMEOUT_MS 500u
#define HR_REMOTE_COMMAND_TIMEOUT_MS 100u
#define HR_PROTOCOL_FUTURE_TOLERANCE_MS 50u
#endif
