#ifndef HR_TASK_CONFIG_H
#define HR_TASK_CONFIG_H
#define HR_MONITOR_PERIOD_MS 10u
#define HR_CHASSIS_PERIOD_MS 1u
#define HR_IMU_FALLBACK_PERIOD_MS 1u
#define HR_COMMAND_PERIOD_MS 5u
#define HR_TASK_HEARTBEAT_TIMEOUT_MS 30u
#define HR_MONITOR_TASK_PRIORITY 5u
#define HR_CHASSIS_TASK_PRIORITY 4u
#define HR_IMU_TASK_PRIORITY 3u
#define HR_COMMAND_TASK_PRIORITY 2u
#endif
